### ISSUE TITLE
Add the EPL license

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/lyo-adaptor-sample-modelling#6]

**Comment by berezovskyi** [comment]
Shall we just add the license to the Github repo root? I think the issue was that its dual EPL/EDL licensed and I was not sure:

* how to reflect it in the single LICENSE file
* if ALL of the source files used this license combo

**Comment by jadelkhoury** [comment]
Sounds reasonable to me. 
Note that we already have the license files under the modeling project (https://github.com/OSLC/lyo-adaptor-sample-modelling/tree/master/toolchain-model/license)

These are the generated files from the adaptor generation (which I discovered is buggy, since they ought to be produced for each adaptor - within the adaptor projects)
